name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  claude-assistant:
    # Only run on PR-related events that contain @claude
    if: |
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude'))
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
      actions: read

    steps:
      - name: Security Check - Validate User Access
        run: |
          ACTOR="${{ github.actor }}"
          echo "Validating access for user: $ACTOR"
          
          # Check if user is organization member
          MEMBERSHIP_STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/orgs/deriv-com/members/$ACTOR" \
            -w "%{http_code}" -o /dev/null)
          
          if [[ "$MEMBERSHIP_STATUS" == "204" ]]; then
            echo "✅ User $ACTOR is a verified organization member"
            exit 0
          fi
          
          # Check if user is repository collaborator
          COLLABORATOR_STATUS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/collaborators/$ACTOR" \
            -w "%{http_code}" -o /dev/null)
          
          if [[ "$COLLABORATOR_STATUS" == "204" ]]; then
            echo "✅ User $ACTOR is a verified repository collaborator"
            exit 0
          fi
          
          echo "❌ Access denied for user: $ACTOR"
          echo "Only organization members and repository collaborators can trigger Claude actions."
          exit 1

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Checkout PR for Fork PRs
        if: github.event_name == 'issue_comment' && github.event.issue.pull_request
        run: |
          # Use GitHub CLI to checkout the PR (works for forks)
          gh pr checkout ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@v1
        timeout-minutes: 60
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allowed_bots: ""
          use_commit_signing: true
