name: Test Simple Workflow Caller

on:
  # Use pull_request_target to allow comments on forked PRs
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  call-simple-test:
    uses: prince-deriv/shared-actions/.github/workflows/test-simple.yml@master
    with:
      message: 'PR #${{ github.event.number }}: ${{ github.event.pull_request.title }}'
    secrets:
      TEST_SECRET: ${{ secrets.TEST_SECRET }} 